### ISSUE TITLE
Hỏi về dataset dùng để train?

### ISSUE THREAD

**Issue by hmtuan0315** [daivuongktx13/VNSpellCorrection#2]
Cho mình hỏi dữ liệu mà bạn train gồm có bao nhiêu dữ liệu và được chuẩn bị như thế nào nhỉ?

**Comment by daivuongktx13** [comment]
mình dùng https://github.com/binhvq/news-corpus. File corpus của người ta có 111M câu nhưng mà mình dùng 12M câu rồi tạo bắt đầu tạo lỗi trên những câu đấy. Sau khi tạo thì được 21M cặp (input, target). Củ thể cách tạo thì mình có ghi trong Readme.

**Comment by hmtuan0315** [comment]
Cảm ơn bạn nhé! Cho mình hỏi là mô hình này bạn train 21M cặp dữ liệu là bạn dùng hạ tầng gì để train và train mất bao lâu vậy bạn?

**Comment by daivuongktx13** [comment]
Mình train trên https://saturncloud.io/ và P100 của Kaggle. Thời gian đầu mình train trên Saturn cho hết tầm 30 tiếng rồi còn lại thì train nhỏ lẻ resume trên Kaggle thêm tầm độ 2 ngày nữa là xong.
