### ISSUE TITLE
[Error] Fail to start app

### ISSUE THREAD

**Issue by linhnguyen1209** [daivuongktx13/VNSpellCorrection#3]
Many thanks for you great works!
I have already installed env and downloaded checkpoint, but failed to start this application (Error in the below image). Please help me!
![image](https://github.com/daivuongktx13/VNSpellCorrection/assets/79707043/3ee10f05-28a4-48b6-8f33-c31506a28eae)

Thank you.

**Comment by daivuongktx13** [comment]
Oops, it's my fault when working with Path. But i don't think we can run server.py in Colab because it will run a website at port 8080. I used to run it on local instead.
